/**
 * @file playlist_entry_control.h
 * @brief Playlist song entry display panel
 * @copyright
 * 2022 Andrew Buettner (ABi)
 *
 * @section LICENSE
 *
 * BachBot - A hymn Midi player for Schlicker organs
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @section DESCRIPTION
 * Because playlists can cause the loading of several "large" songs, this
 * process can potentially take several seconds on an under-powered machine.
 * Rather than bottling up the UI, do most of the loading in a separate thread
 * and force a top-level modal dialog box during the process.
 */

#pragma once

//  system includes
#include <cstdint>  //  uint32_t
#include <functional>  //  std::function
#include <wx/wx.h>  //  wxString

 //  module includes
 // -none-

 //  local includes
#include "main_window.h"  //  PlaylistEntryPanel
#include "play_list.h"  //  PlayListEntry

namespace bach_bot {
namespace ui {

/**
 * @brief On-screen control represenging an item in the playlist.
 */
class PlaylistEntryControl : public PlaylistEntryPanel
{
    /** Callback function format for events generated by this class */
    using CallBack = std::function<void(uint32_t /* song_id */,
                                        PlaylistEntryControl* /* `this` */,
                                        bool /* Function specific */)>;

public:
    /**
     * @brief Constructor
     * @param parent assigned parent window (scroll panel)
     * @param song song configuration
     */
    PlaylistEntryControl(wxWindow *const parent, const PlayListEntry &song);

    /**
     * @brief Get the filename of this song
     * @return file name
     */
    const wxString& get_filename() const;
    
    /**
     * @brief Set this song as "next to be played"
     */
    void set_next();

    /**
     * @brief Set this song as currently playing.
     */
    void set_playing();

    /**
     * @brief Clear "now playing" and "plays next" statuses
     */
    void reset_status();

    /**
     * @brief Set the autoplay checkmark
     * @param autoplay_enabled state to set to
     */
    void set_autoplay(const bool autoplay_enabled);

    //  Allow the player window to set these directly:
    /** Configure button clicked bool: unused (always false) */
    CallBack configure_event;

    /** Autoplay changed event bool: current checkbox state */
    CallBack checkbox_event;

    /** Muve up/down request bool: `true` - up, `false` down */
    CallBack move_event;

    /** Set next song bool: unused (always true) */
    CallBack set_next_event;

    /**
     * @brief Swap this control with another
     * @param other other control to swap with
     */
    void swap(PlaylistEntryControl *const other);

protected:
    virtual void on_configure_clicked(wxCommandEvent& event) override final;
    virtual void on_checkbox_checked(wxCommandEvent &event) override final;
    virtual void on_set_next(wxCommandEvent &event) override final;
    virtual void on_move_up(wxCommandEvent &event) override final;
    virtual void on_move_down(wxCommandEvent &event) override final;

private:
    /**
     * @brief (Re-)Setup the controls (filename, playing, next) based on new
     *        state.
     */
    void setup_widgets();

    /**
     * @brief Dummy callback function to use if callbacks aren't assigned.
     */
    static void dummy_event(uint32_t, PlaylistEntryControl*, bool);

    wxWindow *const m_parent;
    uint32_t m_song_id;
    wxString m_filename;
    bool m_autoplay;
    bool m_up_next;
    bool m_playing;
};

}  //  end ui
}  //  end bach_bot
